### ISSUE TITLE
$data sometimes undefined

### ISSUE THREAD

**Issue by peter-conalgo** [coinkite/coinkite-php#2]
We've seen a two reports now like this:

```
Notice: Undefined variable: data in /.../coinkite/requestor.php on line 56
```

I don't understand the line 56 part, but I do see a path through `function request($method, $endpt, $args=null, $headers=null)` that could cause that message:

If there is no `$args` defined, then I don't think `$data` would be defined at [line 63](https://github.com/coinkite/coinkite-php/blob/master/lib/requestor.php#L63) but that's just based on my skimming, and a no knowledge of how PHP works.

**Comment by BitMari** [comment]
I'm getting that too

**Comment by peter-conalgo** [comment]
May I ask what you have on line 56 of that file?

**Comment by BitMari** [comment]
this is line 56

 curl_setopt($curl, CURLOPT_POSTFIELDS, $data);

**Comment by BitMari** [comment]
hello I'm still getting this error

**Comment by mlawson57** [comment]
Thanks for the heads up BitMari. I will look into this as soon as I can.

**Comment by BitMari** [comment]
Hie

Any luck with that?

**Comment by BitMari** [comment]
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: data

Filename: libraries/CKRequestor.php

Line Number: 56

Backtrace:

File: CKRequestor.php
Line: 56
Function: _error_handler

File: CKRequestor.php
Line: 140
Function: request

**Comment by mlawson57** [comment]
Hey, I'm having some trouble reproducing this error, is there anything you can tell me that might help me out. Thanks!

**Comment by leonar15** [comment]
Just fixed this missing $data variable with https://github.com/coinkite/coinkite-php/pull/3

**Comment by BitMari** [comment]
Thank you very much let me check that.

Regards
